# Generated by Django 2.1.7 on 2019-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('aboutimage', models.ImageField(blank=True, max_length=1000, null=True, upload_to='static/images/', verbose_name='主页动图')),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('aid', models.BigAutoField(primary_key=True, serialize=False)),
                ('home1', models.ImageField(blank=True, max_length=1000, null=True, upload_to='static/swf/', verbose_name='主页动图')),
            ],
        ),
    ]
