# Generated by Django 2.1.7 on 2019-06-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190626_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsimages',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='static/imgs/', verbose_name='新闻动图'),
        ),
    ]
